### ISSUE TITLE
GtkDirectoryList Error building template

### ISSUE THREAD

**Issue by gavr123456789** [ToshioCP/Gtk4-tutorial#10]
There are Gtk-CRITICAL when run list3.c example.   
```shell
sh-5.1$ ./a.out 

(a.out:33843): Gtk-CRITICAL **: 03:22:40.840: Error building template for list item: .:0:0: No function named `get_file_name`.

(a.out:33843): Gtk-CRITICAL **: 03:22:40.840: Error building template for list item: .:0:0: No function named `get_file_name`.

(a.out:33843): Gtk-CRITICAL **: 03:22:40.840: Error building template for list item: .:0:0: No function named `get_file_name`.
```  
Compiled with gcc \`pkg-config --cflags gtk4\` c.c \`pkg-config --libs gtk4\`
  
GTK version: 4.2.1-1
Linux: Arch

**Comment by gavr123456789** [comment]
Thanks, now it works, its really the best guide for GTK 4 now.  
I think there should be a mention of this in section 24.

**Comment by ToshioCP** [comment]
Thank you for your suggestion.
It is helpful to improve this tutorial.
I've modified section 24 and put some explanation about `-Wl,--export-dynamic` option.
