### ISSUE TITLE
The error was 'GLXBadFBConfig'.

### ISSUE THREAD

**Issue by serdio-nerd** [ToshioCP/Gtk4-tutorial#15]
I need  to fix this,help is needed.
Error:-----
(a.out:8740): Gtk-WARNING **: 11:21:38.293: Unknown key gtk-button-images in /home/user/.config/gtk-4.0/settings.ini

(a.out:8740): Gtk-WARNING **: 11:21:38.297: Unknown key gtk-menu-images in /home/user/.config/gtk-4.0/settings.ini

(a.out:8740): Gtk-WARNING **: 11:21:38.297: Unknown key gtk-toolbar-style in /home/user/.config/gtk-4.0/settings.ini

(a.out:8740): Gdk-WARNING **: 11:21:38.446: The program 'a.out' received an X Window System error.
This probably reflects a bug in the program.
The error was 'GLXBadFBConfig'.
  (Details: serial 229 error_code 167 request_code 152 (GLX) minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

**Comment by ToshioCP** [comment]
Thank you for the post.

But sorry, I haven't found the solution.
There's a website 'Gnome Discourse'in which Gtk experts answer questions.
The address is:

https://discourse.gnome.org/

I recommend you to post your question to it with more detailed explanation.
(For example, your program, your system and so on.)

**Comment by ToshioCP** [comment]
I close this issue for no further information.
