### ISSUE TITLE
`! LaTeX Error: Something's wrong--perhaps a missing \item.` on `rake pdf`

### ISSUE THREAD

**Issue by nmtake** [ToshioCP/Gtk4-tutorial#16]
Hi, thanks for the tutorial!  I ran `rake pdf` on HEAD (fbbaa8c) but got this error:

```
> rake cleanlatex pdf
[...]
(/usr/share/texmf-dist/tex/latex/microtype/mt-msb.cfg) (./abstract.tex

! LaTeX Error: Something's wrong--perhaps a missing \item.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

l.12   S
      ection 3 to 21 describes basics and the example is a simple editor
?
```

Generated `latex/abstract.tex`:

```
\hypertarget{about-this-tutorial}{%
\paragraph{About this tutorial}\label{about-this-tutorial}}

This tutorial is aimed at beginners who are learning Gobject system. One
[...]
```

Environments:

* LuaHBTeX, Version 1.13.2 (TeX Live 2021/Arch Linux)
* LaTeX2e <2021-11-15> patch level 1
* L3 programming layer <2021-11-22>
* pandoc 2.14.1 Compiled with pandoc-types 1.22, texmath 0.12.3.1, skylighting 0.11, citeproc 0.4.1, ipynb 0.1.0.1

---

It seems that `abstract` environments can't contain `\paragraph`s:

```
> cat foo.tex
\documentclass{article}
\begin{document}
\begin{abstract}
\paragraph{About this tutorial}This tutorial aimed...
\end{abstract}
\end{document}

> lualatex foo.tex
[...]
(./foo.tex
[...]
! LaTeX Error: Something's wrong--perhaps a missing \item.
```

and here are related discussions and workarounds:

* https://tex.stackexchange.com/questions/74371/subdividing-structured-abstracts/74374#74374
* https://github.com/latex3/latex2e/issues/248
* https://www.nlm.nih.gov/bsd/policy/structured_abstracts.html

**Comment by ToshioCP** [comment]
Dear nmtake,

Thank you for posting the issue.

There was a bug.
The problem was the conflict between abstract environment and paragraph command, as you mentioned.
So I decided to remove abstract environment.
Lib/lib_gen_main_tex.rb has been changed for that.
I've pushed the change to the github repository.
See the commit so that you can see the detail.

Thank you again for your contribution.

Toshio Sekiya

**Comment by ToshioCP** [comment]
Bug fixed.

**Comment by nmtake** [comment]
Confirmed `rake** pdf` built PDF successfully on ced4e0c. Thank you!
