### ISSUE TITLE
Found a small typo in section 3.

### ISSUE THREAD

**Issue by imxtx** [ToshioCP/Gtk4-tutorial#25]
Found a small typo in section 3 :[GtkApplicationWindow](https://toshiocp.github.io/Gtk4-tutorial/sec3.html).

Extra space in the third line: Now rewrite the program and use **GtkAppliction Window**.

""GtkAppliction Window"" --> ""GtkApplictionWindow""

By the way, your tutorial is really great! It helped me a lot. Thank yoooooooou!

**Comment by imxtx** [comment]
Found another one in [section 4](https://toshiocp.github.io/Gtk4-tutorial/sec4.html).

In the first subheading: Gtkbox --> GtkBox

**Comment by ToshioCP** [comment]
Hi, Imxtx.
Thank you very much for posting the issue.
It helps me to improve this tutorial.

By the way, I couldn't find the first typo error (Section 3).
I've checked the source code.

 ~~~
$ grep 'GtkApplication Window' *.src.md
~~~

But nothing appears.
So, check it again and tell me the typo error again.

The second typo error (Gtkbox) has already been corrected (but not uploaded yet).

**Comment by imxtx** [comment]
> Hi, Imxtx. Thank you very much for posting the issue. It helps me to improve this tutorial.
> 
> By the way, I couldn't find the first typo error (Section 3). I've checked the source code.
> 
> ```
> $ grep 'GtkApplication Window' *.src.md
> ```
> 
> But nothing appears. So, check it again and tell me the typo error again.
> 
> The second typo error (Gtkbox) has already been corrected (but not uploaded yet).

Here it is.
https://github.com/ToshioCP/Gtk4-tutorial/blob/main/src/sec3.src.md?plain=1#L268

**Comment by ToshioCP** [comment]
Thank you very much, Imxtx.

The typo errors have fixed.
