### ISSUE TITLE
Link problem in section 8

### ISSUE THREAD

**Issue by imxtx** [ToshioCP/Gtk4-tutorial#28]
Missing a left `[` for the markdown link at the end of [this line](https://github.com/ToshioCP/Gtk4-tutorial/blob/e8b2f9ad905ff8d2f1972d13b6530d440fb5e3b2/gfm/sec8.md?plain=1#L55).

**Comment by ToshioCP** [comment]
Thank you for pointing out the error.
It has been fixed.
