### ISSUE TITLE
Can i translate to spanish?

### ISSUE THREAD

**Issue by cjdg** [ToshioCP/Gtk4-tutorial#30]
I would like to translate it to spanish

**Comment by ToshioCP** [comment]
Thank you for the proposal, Cristian.
It's great if you would translate this tutorial to Spanish.

I think it's a good way to make your own repository and put the Spanish version in it.
Please let me know your repository address when you finish the translation.
I will put a link to your repository in my Readme file.
The license of this tutorial is public domain, so please put the same license to your repository.

**Comment by cjdg** [comment]
Ok

**Comment by cjdg** [comment]
Already started, https://github.com/cjdg/Gtk4-tutorial-spanish

**Comment by ToshioCP** [comment]
Dear Cristian,

I saw your repository.
It is better to translate files in `src` directory and run `rake`, then the files in `gfm`, which are linked from `Readme.md`, will be created automatically.
In addition, you can make HTML files in docs by `rake html` and a PDF file by `rake pdf`.
Those process are explained in:

https://github.com/ToshioCP/Gtk4-tutorial/blob/main/gfm/Readme_for_developers.md

If you have any questions about it, post them to this issue page,

You also use GitHub pages to publish your HTML document like this.

https://toshiocp.github.io/Gtk4-tutorial/

When you finish your work, please let me know it.
I'll put the link to your repository in the `Readme.md` in my tutorial.
Thanks.

**Comment by ToshioCP** [comment]
This issue is ablut the translation.
It is not the direct issue for this repository.
So, I think it is not a problem if the issue is closed.
