### ISSUE TITLE
https://github.com/ToshioCP/Gtk4-tutorial/blob/main/gfm/sec15.md - can you add the command to compile it from the commandline?

### ISSUE THREAD

**Issue by rubyFeedback** [ToshioCP/Gtk4-tutorial#34]
https://github.com/ToshioCP/Gtk4-tutorial/blob/main/gfm/sec15.md - can you add the command to compile it from the commandline?

I think it would be useful to be able to quickly copy/paste the command. One can assemble it from
the www but I think having it in the .md file on the end of that file would be very convenient. Thank you for reading!

**Comment by ToshioCP** [comment]
Hi, rubyFeedback.
Thank you for posting the message to the issue page.

How to compile and run the application is shown in the next section (section 16).
See the beginning of the section 16.

By the way, I recommend you to download the repository, then you can obtain all the source codes.
So you don't need to type any codes.
Just compile and run.

If you have more questions, feel free to post a message here.

Toshio Sekiya

**Comment by ToshioCP** [comment]
There seems no more problem under this issue thread.
So, it is closed now.
