### ISSUE TITLE
Line numbers copied along with code.

### ISSUE THREAD

**Issue by RageshAntony** [ToshioCP/Gtk4-tutorial#35]
When trying to copy a codeblock from a tutorial section, the line numbers also being copied along with the code even with the copy button on top right

please fix them

**Comment by ToshioCP** [comment]
Thank you for posting the issue, RageshAntony.

The line numbers are added for the convenience for readers.
Source codes are put under `src` directory.
For example, `example1.c` in the section 3 is located at `src/misc/example1.c`.
Therefore, please clone the repository into your local computer and see the files under `src` directory.
The line numbers are necessary for the explanation in the document so it can't be left out.

If you have any problem more, feel free to post issues.

Toshio Sekiya

**Comment by ToshioCP** [comment]
Thank you for posting the issue, RageshAntony.

I posted minitues ago, but there was a mistake in it so I deleted it.
This is the second post which is correct one.

The line numbers are for readers to easily find a target line in the source code.
So it can't be left out.
But instead, there are source codes below `src` directory.
For example, `pr1.c` in the section 3 is located at `src/misc/pr1.c`.

So, please clone this repository to your local computer and see the files below the `src` directory.

If you have other problems, feel free to post issues.

Toshio Sekiya
