### ISSUE TITLE
What's the license of these tutorials?

### ISSUE THREAD

**Issue by leinardi** [ToshioCP/Gtk4-tutorial#46]
Hi, I'm currently writing some documentation for Kotlin/Native bindings of GTK4 and I was wondering what license are they using and if I can port some of them to the K/N bindings documentation that is currently licensed under CC-BY-SA 3.0.

**Comment by ToshioCP** [comment]
Hello, Roberto.
The license is GPL.
See [Section 1 Prerequisite and License](https://github.com/ToshioCP/Gtk4-tutorial/blob/main/gfm/sec1.md).

**Comment by leinardi** [comment]
I see, I have to update to version 4.0 to be compatible: https://creativecommons.org/2015/10/08/cc-by-sa-4-0-now-one-way-compatible-with-gplv3/

Btw have you considered using [GFDL](https://www.gnu.org/licenses/fdl-1.3.html) instead of GPL? It seems more appropriate for documentation than GPL and  CC-BY-SA 3.0 is already compatible with it.

**Comment by ToshioCP** [comment]
Thank you for your suggestion.
I'll consider that as soon as possible.

**Comment by ToshioCP** [comment]
I announced the following in the `README.md`.

New licenses, one of which is GFDL1.3 for documents and the other is GPL3 for programs, are under consideration.
The decision will be made on 15/April/2023.

**Comment by leinardi** [comment]
Nice! Thanks!

**Comment by ToshioCP** [comment]
The license has already been changed but the issue still remained.
Now it is closed.
