### ISSUE TITLE
Issue in the Glib Installation Section

### ISSUE THREAD

**Issue by lilithi** [ToshioCP/Gtk4-tutorial#5]
I am working through your tutorial, and it's been a big help with getting started. I did encounter an issue at the very beginning, and including a note about how to resolve this may help other beginners who encounter this issue. In the [Glib Installation](https://github.com/ToshioCP/Gtk4-tutorial/blob/main/gfm/sec2.md) section, when I ran `meson --prefix $HOME/local _build` I got the error `meson.build:1:0: ERROR: Compiler cc can not compile programs.` I was able to resolve it with `sudo apt install gcc-multilib` The solution was not obvious from the meson-log.txt

In case its relevant, I'm on Linux Mint 20, which is based on Ubuntu 20.04.

Edit: For anyone looking for a solution to this problem in the future, I would guess `apt-get install libc-dev` is what is most likely to fix your issues

**Comment by dvergeylen** [comment]
I also experienced a problem with Glib when compiling it next to Gtk4.

Although setting the env variables to appropriate values:
```bash
export LD_LIBRARY_PATH="/path/to/glib-2.67.2/lib/x86_64-linux-gnu/:/path/to/gtk4-lib/lib/x86_64-linux-gnu/"
```
my programs crashed when using a FileChooser:

```bash
GLib-GIO-ERROR **: 21:51:27.033: Settings schema 'org.gtk.gtk4.Settings.FileChooser' is not installed
```
The problem is that Glib doesn't know the appropriate schemas for FileChooser, which are in the (freshly compiled) gtk4 directory (share/glib-2.0/schemas). You can compile them via `glib-compile-schemas share/glib-2.0/schemas/` (from the gtk4 installation directory). This will produce a `gschemas.compiled`.

You then set `GSETTINGS_SCHEMA_DIR` accordingly:
```bash
export GSETTINGS_SCHEMA_DIR=/path/to/gtk4-lib/share/glib-2.0/schemas
```

[Source](https://discourse.gnome.org/t/testing-gtk4-installed-on-opt-gtk-some-programs-can-not-load-their-settings/1134)

**Comment by ToshioCP** [comment]
Dear Lilithi

Thank you for the information. I use UBUNTU 20.10 and I've built gtk4 on it. I checked the package gcc-multilib. Then I found the package is NOT installed in my computer.
So, It might not the direct cause of your problem, But I don't have enough knowledge to make things clear.

**Comment by lilithi** [comment]
The meson-logs.txt outputs
```
Sanity check compile stderr:
/usr/bin/ld: cannot find Scrt1.o: No such file or directory
/usr/bin/ld: cannot find crti.o: No such file or directory
collect2: error: ld returned 1 exit status

meson.build:1:0: ERROR: Compiler cc can not compile programs.
```

Searches about this lead to a [Stack Exchange](https://stackoverflow.com/questions/6329887/compiling-problems-cannot-find-crt1-o) question from 2011. The problem must be common as replies are from as late as 2017. It contains a ton of answers, but my guess is this solution most likely to be helpful:

> Seems that while you were playing with llvm/clang you(or the package manager) removed previously existing standard C library development package (eglibc on Debian) or maybe you didn't have it installed in the first place, thus you need to reinstall it, now that you reverted back to gcc.
> 
> You can do so like this on Debian:
> 
> `aptitude show libc-dev`
> 
> Ubuntu:
> 
> `apt-get install libc-dev`
> 

That said, the answers are all over the place, and unfortunately, I don't know enough to be certain this would be helpful.

**Comment by ToshioCP** [comment]
Maybe the message in Stack Exchange is the answer,
In my computer, libc6-dev (libc-dev is a meta package that points libc6-dev) is installed.
It is an indispensable package for gcc.
