### ISSUE TITLE
Section 12: Wrong line references  in "Explanation of Save and saveas functions"

### ISSUE THREAD

**Issue by igormorgado** [ToshioCP/Gtk4-tutorial#8]
The bullets related to the functions in `saveas_dialog_response`, `tfe_text_view_save` and  `tfe_text_view_saveas` are pointing to wrong lines. That creates a very complicated explanation. 

Just to make things easier to search in the file, the problem starts at "`Tfe_text_view_save` function." and ends at "Finally, it calls `tfe_text_view_save` to save the buffer to the file."

Hope it helps.

**Comment by ToshioCP** [comment]
Thank you Igor for pointing out the mistake.
The source file "tfetextview.c" had been upgraded, but document has still had the old description.
I also found bugs in tfetextview.c
So I updated several files.
The part you pointed out has been changed a lot.
